/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from '@angular/core/src/render/api';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from './page.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/element';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from 'ionic-angular/components/app/app';
import * as import11 from '@angular/core/src/linker/component_factory';
const styles_Page:any[] = [];
const nodeDebugInfos_Page0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([],null,{})];
var renderType_Page:import1.RenderComponentType = null;
class _View_Page0 extends import2.DebugAppView<import3.Page> {
  _text_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import6.AppElement) {
    super(_View_Page0,renderType_Page,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectionStrategy.CheckAlways,nodeDebugInfos_Page0);
  }
  createInternal(rootSelector:string):import6.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n  Sup Yo\n  ',this.debug(0,0,0));
    this.init([],[this._text_0],[],[]);
    return null;
  }
}
export function viewFactory_Page0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import6.AppElement):import2.AppView<import3.Page> {
  if ((renderType_Page === null)) { (renderType_Page = viewUtils.createRenderComponentType('/Users/joshthomas/Workspace/tree-shake-ionic2/typescript-only-es2015-offlinetemplates-ionic2/src/app/page.component.ts class Page - inline template',0,import9.ViewEncapsulation.None,styles_Page)); }
  return new _View_Page0(viewUtils,parentInjector,declarationEl);
}
const styles_Page_Host:any[] = [];
const nodeDebugInfos_Page_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import3.Page],import3.Page,{})];
var renderType_Page_Host:import1.RenderComponentType = null;
class _View_Page_Host0 extends import2.DebugAppView<any> {
  _el_0:any;
  private _appEl_0:import6.AppElement;
  _Page_0_4:import3.Page;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import6.AppElement) {
    super(_View_Page_Host0,renderType_Page_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectionStrategy.CheckAlways,nodeDebugInfos_Page_Host0);
  }
  createInternal(rootSelector:string):import6.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ion-page',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import6.AppElement(0,null,this,this._el_0);
    var compView_0:any = viewFactory_Page0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Page_0_4 = new import3.Page(this.parentInjector.get(import10.App));
    this._appEl_0.initComponent(this._Page_0_4,[],compView_0);
    compView_0.create(this._Page_0_4,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.Page) && (0 === requestNodeIndex))) { return this._Page_0_4; }
    return notFoundResult;
  }
}
function viewFactory_Page_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import6.AppElement):import2.AppView<any> {
  if ((renderType_Page_Host === null)) { (renderType_Page_Host = viewUtils.createRenderComponentType('',0,null,styles_Page_Host)); }
  return new _View_Page_Host0(viewUtils,parentInjector,declarationEl);
}
export const PageNgFactory:import11.ComponentFactory<import3.Page> = new import11.ComponentFactory<import3.Page>('ion-page',viewFactory_Page_Host0,import3.Page);